# Generated by Django 5.0.6 on 2026-05-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyJobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(choices=[('recommendations', 'Priporočila knjig'), ('matching', 'Ujemanje bralcev in skupin'), ('top_books', 'Top knjige')], max_length=50, unique=True, verbose_name='Ime joba')),
                ('last_run_at', models.DateTimeField(verbose_name='Zadnji uspešen zagon')),
                ('users_processed', models.IntegerField(default=0, verbose_name='Število obdelanih uporabnikov')),
            ],
            options={
                'verbose_name': 'Log dnevnega joba',
                'verbose_name_plural': 'Logi dnevnih jobov',
            },
        ),
    ]
