# Generated by Django 5.0.6 on 2026-04-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ime in priimek')),
                ('bio', models.TextField(blank=True, verbose_name='Biografija')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='Leto rojstva')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Avtor',
                'verbose_name_plural': 'Avtorji',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Ime zvrsti')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='URL oznaka')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zvrst',
                'verbose_name_plural': 'Zvrsti',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Naslov')),
                ('isbn', models.CharField(blank=True, help_text='13-mestna številka ISBN (neobvezno).', max_length=13, verbose_name='ISBN')),
                ('publication_year', models.IntegerField(blank=True, null=True, verbose_name='Leto izdaje')),
                ('publisher', models.CharField(blank=True, max_length=150, verbose_name='Založba')),
                ('description', models.TextField(blank=True, help_text='Kratek opis vsebine knjige.', verbose_name='Opis')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='Naslovnica')),
                ('language', models.CharField(choices=[('sl', 'Slovenščina'), ('en', 'Angleščina'), ('de', 'Nemščina'), ('fr', 'Francoščina'), ('it', 'Italijanščina'), ('es', 'Španščina'), ('hr', 'Hrvaščina'), ('sr', 'Srbščina'), ('other', 'Drugo')], default='sl', max_length=10, verbose_name='Jezik')),
                ('page_count', models.IntegerField(blank=True, null=True, verbose_name='Število strani')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Povprečna ocena')),
                ('ratings_count', models.IntegerField(default=0, verbose_name='Število ocen')),
                ('is_approved', models.BooleanField(default=True, help_text='Knjige, ki jih dodajo uporabniki, mora potrditi administrator.', verbose_name='Potrjeno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(related_name='books', to='books.author', verbose_name='Avtorji')),
                ('genres', models.ManyToManyField(blank=True, related_name='books', to='books.genre', verbose_name='Zvrsti')),
            ],
            options={
                'verbose_name': 'Knjiga',
                'verbose_name_plural': 'Knjige',
                'ordering': ['title'],
            },
        ),
    ]
