# Generated by Django 5.0.6 on 2026-05-18 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(unique=True, verbose_name='Mesto')),
                ('average_rating', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Povprečna ocena ob izračunu')),
                ('ratings_count', models.IntegerField(verbose_name='Število ocen ob izračunu')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_entries', to='books.book', verbose_name='Knjiga')),
            ],
            options={
                'verbose_name': 'Top knjiga',
                'verbose_name_plural': 'Top knjige',
                'ordering': ['rank'],
            },
        ),
    ]
