# Generated by Django 5.0.6 on 2026-04-17 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, help_text='Do 300 znakov.', max_length=300, verbose_name='Kratka biografija')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Profilna slika')),
                ('location', models.CharField(blank=True, help_text='Pomembno za izposojo knjig med uporabniki.', max_length=100, verbose_name='Mesto / regija')),
                ('reliability_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Povprečje ocen po izposojah (Faza 5).', max_digits=3, verbose_name='Ocena zanesljivosti')),
                ('cluster_id', models.IntegerField(blank=True, help_text='Rezultat K-Means gručenja bralcev (Faza 4).', null=True, verbose_name='Gruča (UI model)')),
                ('is_public', models.BooleanField(default=True, verbose_name='Javni profil')),
                ('show_in_matches', models.BooleanField(default=True, help_text='Če je izklopljeno, tvoj profil ne bo predlagan drugim bralcem.', verbose_name='Sodeluj v sistemu ujemanj')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Uporabnik')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profili',
            },
        ),
    ]
