# Generated by Django 5.0.6 on 2026-04-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.CharField(blank=True, choices=[('', '— Izberi regijo —'), ('osrednjeslovenska', 'Osrednjeslovenska'), ('gorenjska', 'Gorenjska'), ('savinjska', 'Savinjska'), ('podravska', 'Podravska'), ('pomurska', 'Pomurska'), ('koroska', 'Koroška'), ('zasavska', 'Zasavska'), ('posavska', 'Posavska'), ('jv_slovenija', 'Jugovzhodna Slovenija'), ('goriska', 'Goriška'), ('obalno_kraska', 'Obalno-kraška'), ('primorsko_notranjska', 'Primorsko-notranjska'), ('drugo', 'Drugo / tujina')], default='', help_text='Tvoja statistična regija (uporablja se za izposojo in predlaganje regijskih skupin).', max_length=30, verbose_name='Regija'),
        ),
        migrations.AddField(
            model_name='profile',
            name='reliability_count',
            field=models.IntegerField(default=0, verbose_name='Število ocen zanesljivosti'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cluster_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Gruča (UI model)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, help_text='Npr. konkreten kraj, če želiš to povedati drugim bralcem.', max_length=100, verbose_name='Kraj (neobvezno)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reliability_score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Povprečje ocen po izposojah.', max_digits=3, verbose_name='Ocena zanesljivosti'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_in_matches',
            field=models.BooleanField(default=True, verbose_name='Sodeluj v sistemu ujemanj'),
        ),
    ]
