# Generated by Django 5.0.6 on 2026-04-21 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Zadnje sporočilo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_a', to=settings.AUTH_USER_MODEL)),
                ('participant_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pogovor',
                'verbose_name_plural': 'Pogovori',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('user', 'Uporabniško'), ('system', 'Sistemsko')], default='user', max_length=10, verbose_name='Vrsta')),
                ('content', models.TextField(max_length=2000, verbose_name='Vsebina')),
                ('is_read', models.BooleanField(default=False, verbose_name='Prebrano')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation')),
                ('sender', models.ForeignKey(blank=True, help_text='Null pri sistemskih sporočilih.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sporočilo',
                'verbose_name_plural': 'Sporočila',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(check=models.Q(('participant_a', models.F('participant_b')), _negated=True), name='messaging_conversation_different_participants'),
        ),
    ]
