# Generated by Django 5.0.6 on 2026-05-12 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('reading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Opomba')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_books', to='books.book', verbose_name='Knjiga')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_books', to=settings.AUTH_USER_MODEL, verbose_name='Lastnik')),
            ],
            options={
                'verbose_name': 'Knjiga v domači knjižnici',
                'verbose_name_plural': 'Knjige v domači knjižnici',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'book')},
            },
        ),
    ]
