# Generated by Django 5.0.6 on 2026-04-19 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.DecimalField(decimal_places=3, help_text='0–1, koliko žanri skupine ustrezajo uporabnikovemu okusu.', max_digits=4, verbose_name='Stopnja ujemanja')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Razlog predloga')),
                ('is_dismissed', models.BooleanField(default=False, verbose_name='Uporabnik skril')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='groups.readinggroup', verbose_name='Predlagana skupina')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='Uporabnik')),
            ],
            options={
                'verbose_name': 'Predlagana skupina',
                'verbose_name_plural': 'Predlagane skupine',
                'ordering': ['-match_score'],
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.CreateModel(
            name='UserMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.DecimalField(decimal_places=3, help_text='Kosinusna podobnost bralnih profilov (0–1).', max_digits=4, verbose_name='Podobnost')),
                ('shared_genres', models.CharField(blank=True, help_text='Besedilni opis skupnih najljubših žanrov (za razlago).', max_length=255, verbose_name='Skupni žanri')),
                ('cluster_id', models.IntegerField(blank=True, help_text='V kateri gruči se nahajata oba uporabnika.', null=True, verbose_name='ID gruče')),
                ('is_dismissed', models.BooleanField(default=False, verbose_name='Uporabnik skril')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_a', to=settings.AUTH_USER_MODEL, verbose_name='Uporabnik A')),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_b', to=settings.AUTH_USER_MODEL, verbose_name='Uporabnik B')),
            ],
            options={
                'verbose_name': 'Ujemanje bralcev',
                'verbose_name_plural': 'Ujemanja bralcev',
                'ordering': ['-similarity_score'],
                'unique_together': {('user_a', 'user_b')},
            },
        ),
    ]
