# Generated by Django 5.0.6 on 2026-04-20 12:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('new', 'Novo'), ('very_good', 'Zelo dobro'), ('good', 'Dobro'), ('poor', 'Slabo (opazna uporaba)')], default='good', max_length=20, verbose_name='Stanje izvoda')),
                ('max_loan_days', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Največja doba izposoje (dni)')),
                ('notes', models.TextField(blank=True, help_text='Npr. podpis avtorja, zapiski v knjigi, posebni pogoji prevzema.', verbose_name='Dodatne opombe')),
                ('status', models.CharField(choices=[('available', 'Na voljo'), ('reserved', 'Rezervirano'), ('borrowed', 'Izposojeno'), ('inactive', 'Neaktivno')], default='available', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_offers', to='books.book', verbose_name='Knjiga')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_offers', to=settings.AUTH_USER_MODEL, verbose_name='Lastnik')),
            ],
            options={
                'verbose_name': 'Ponudba izposoje',
                'verbose_name_plural': 'Ponudbe izposoje',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Zakaj te knjiga zanima?', verbose_name='Spremno sporočilo')),
                ('status', models.CharField(choices=[('pending', 'Čaka na odgovor'), ('accepted', 'Sprejeto'), ('rejected', 'Zavrnjeno'), ('returned', 'Vrnjeno'), ('cancelled', 'Preklicano')], default='pending', max_length=20, verbose_name='Status')),
                ('loan_start', models.DateField(blank=True, null=True, verbose_name='Datum izposoje')),
                ('loan_end', models.DateField(blank=True, null=True, verbose_name='Datum vračila')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests', to=settings.AUTH_USER_MODEL, verbose_name='Prosilec')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='loans.loanoffer', verbose_name='Ponudba')),
            ],
            options={
                'verbose_name': 'Prošnja za izposojo',
                'verbose_name_plural': 'Prošnje za izposojo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Ocena (1–5)')),
                ('comment', models.TextField(blank=True, verbose_name='Komentar (neobvezno)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='loans.loanrequest', verbose_name='Izposoja')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_reviews_received', to=settings.AUTH_USER_MODEL, verbose_name='Ocenjeni')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_reviews_given', to=settings.AUTH_USER_MODEL, verbose_name='Ocenjevalec')),
            ],
            options={
                'verbose_name': 'Ocena izposoje',
                'verbose_name_plural': 'Ocene izposoje',
                'ordering': ['-created_at'],
                'unique_together': {('loan_request', 'reviewer')},
            },
        ),
    ]
