# Generated by Django 5.0.6 on 2026-04-19 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Ime skupine')),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True, verbose_name='URL oznaka')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Opis skupine')),
                ('visibility', models.CharField(choices=[('public', 'Javna'), ('private', 'Zasebna')], default='public', max_length=20, verbose_name='Vidnost')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='group_covers/', verbose_name='Naslovnica skupine')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(blank=True, help_text='Zvrsti, ki jih ta skupina pokriva (za UI ujemanje).', related_name='groups', to='books.genre', verbose_name='Povezane zvrsti')),
                ('owner', models.ForeignKey(blank=True, help_text='Null za sistemske skupine (samodejno ustvarjene po žanrih).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_groups', to=settings.AUTH_USER_MODEL, verbose_name='Lastnik')),
            ],
            options={
                'verbose_name': 'Skupina',
                'verbose_name_plural': 'Skupine',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000, verbose_name='Vsebina')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to=settings.AUTH_USER_MODEL, verbose_name='Pošiljatelj')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='groups.readinggroup', verbose_name='Skupina')),
            ],
            options={
                'verbose_name': 'Sporočilo v skupini',
                'verbose_name_plural': 'Sporočila v skupini',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Član'), ('moderator', 'Moderator'), ('owner', 'Lastnik')], default='member', max_length=20, verbose_name='Vloga')),
                ('is_approved', models.BooleanField(default=True, help_text='Pri zasebnih skupinah mora lastnik odobriti.', verbose_name='Potrjeno')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Uporabnik')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.readinggroup', verbose_name='Skupina')),
            ],
            options={
                'verbose_name': 'Članstvo',
                'verbose_name_plural': 'Članstva',
                'ordering': ['-joined_at'],
                'unique_together': {('user', 'group')},
            },
        ),
    ]
