# Generated by Django 5.0.6 on 2026-04-20 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='readinggroup',
            name='region',
            field=models.CharField(choices=[('all', 'Vse regije (skupina za celotno Slovenijo)'), ('osrednjeslovenska', 'Osrednjeslovenska'), ('gorenjska', 'Gorenjska'), ('savinjska', 'Savinjska'), ('podravska', 'Podravska'), ('pomurska', 'Pomurska'), ('koroska', 'Koroška'), ('zasavska', 'Zasavska'), ('posavska', 'Posavska'), ('jv_slovenija', 'Jugovzhodna Slovenija'), ('goriska', 'Goriška'), ('obalno_kraska', 'Obalno-kraška'), ('primorsko_notranjska', 'Primorsko-notranjska'), ('drugo', 'Drugo / tujina')], default='all', help_text='Izberi »Vse regije«, če skupina ni vezana na konkretno regijo.', max_length=30, verbose_name='Regija'),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.readinggroup'),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='role',
            field=models.CharField(choices=[('member', 'Član'), ('moderator', 'Moderator'), ('owner', 'Lastnik')], default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='content',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='groups.readinggroup'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='groups', to='books.genre', verbose_name='Povezane zvrsti'),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_groups', to=settings.AUTH_USER_MODEL, verbose_name='Lastnik'),
        ),
    ]
