# Generated by Django 5.0.6 on 2026-04-19 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=3, help_text='Kosinusna podobnost (0–1).', max_digits=4, verbose_name='Ocena relevantnosti')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Razlog priporočila')),
                ('is_dismissed', models.BooleanField(default=False, help_text='Če je True, predloga ne prikažemo več.', verbose_name='Uporabnik zavrnil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='books.book', verbose_name='Priporočena knjiga')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL, verbose_name='Uporabnik')),
            ],
            options={
                'verbose_name': 'Priporočilo',
                'verbose_name_plural': 'Priporočila',
                'ordering': ['-score'],
                'unique_together': {('user', 'book')},
            },
        ),
    ]
